<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>C:\PwizDeploy\core\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="pwiz_bindings_cli">
      <HintPath>..\..\..\..\..\PwizDeploy\core\pwiz_bindings_cli.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
